Completed react-events -- Joshua Preciado
joshuapreciado/m3-0323-code-solutions pull request #7
Opened 2023-03-28 04:06 UTC by joshuapreciado

![image](https://user-images.githubusercontent.com/78586776/228125440-3589c2cb-06f8-430a-918d-3a379e0bbe2c.png)

2023-03-28 04:11 UTC, dseong0224 requested changes
pls include a gif that shows the buttons' functionality

2023-03-28 04:16 UTC, joshuapreciado commented
https://gyazo.com/8f0c6a60873211d4ed586a6e5c2a9c44

2023-03-29 01:42 UTC, joshuapreciado commented
https://gyazo.com/9bc47ed384f88351597891a46c212e00

2023-03-29 01:45 UTC, dseong0224 approved these changes

2023-03-29 01:45 UTC, merged